# frozen_string_literal: true

<% module_namespacing do -%>
class <%= class_name %> < <%= parent_class_name.classify %>
  # main config ...............................................................
  audited
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  <% attributes.select(&:reference?).each do |attribute| -%>
  belongs_to :<%= attribute.name %><%= ', polymorphic: true' if attribute.polymorphic? %>
  <% end -%>

  # validations ...............................................................
  #validates_presence_of <% attributes.each_with_index do |attribute, i| -%><% unless attribute.name == 'id' -%> :<%= attribute.name %><%= "," if (i + 1) < attributes.size %><% end -%><% end -%>

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
<% end -%>
