# frozen_string_literal: true

class TbCargo < ActiveRecord::Base
  # main config ...............................................................
  audited
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :tb_empregados, dependent: :restrict_with_error

  # validations ...............................................................
  validates_presence_of :nome, :salario

  # callbacks .................................................................
  before_save :set_chave
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private
  def set_chave
    self.chave = self.nome.downcase.gsub(' ', '').remover_acentos
  end
end
