# frozen_string_literal: true

class TbResposta < ActiveRecord::Base
  # main config ...............................................................
  audited
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  attr_accessor :nme_pergunta, :descricao_pergunta
  # relationships .............................................................
  belongs_to :tb_avaliacao
  belongs_to :tb_pergunta
  # validations ...............................................................
  validates_presence_of :tb_avaliacao_id, :tb_pergunta_id, :nota, :obs

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  enum nota: {
      ruim: 1,
      medio: 2,
      bom: 3,
      otimo: 4,
      perfeito: 5
  }
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
